package com.roguelikedeckbuilder.mygame.combat.effect;

public enum EffectName {
    CONSTITUTION_ONE,
    DAMAGE_A_BIT,
    DAMAGE_MANY_TIMES,
    DEFEND_SOME,
    DEFEND_TWICE_A_BIT,
    DISCARD_RANDOM_CARD_ONE,
    DRAW_CARD_ONE,
    GAIN_ENERGY_ONE,
    GOLD_BONUS_BIG,
    HEAL_SMALL,
    HIGH_DAMAGE_ONCE,
    MAX_HP_CHANGE_DOWN_ONE,
    MAX_HP_CHANGE_UP_ONE,
    NOTHING,
    STRENGTH_ONE,
    TRUE_DAMAGE_FLAT_MODERATE,
    TRUE_DAMAGE_PERCENT_SMALL
}
