package com.roguelikedeckbuilder.mygame.tracking.trigger;

public enum TriggerName {
    DRAW_CARD,
    END_OF_TURN,
    EVERY_START_OF_BATTLE,
    EVERY_TURN_AFTER_TAKING_20_DAMAGE,
    LAST_THREE_DAMAGE_DEALT_GREATER_THAN_30,
    NOTHING,
    ONCE_PER_TURN_AFTER_ENEMY_USES_ABILITY,
    START_OF_TURN,
    PLAYER_TOOK_DAMAGE,
    DAMAGE_IN_ONE_HIT_GTE_12,
    DAMAGE_IN_ONE_HIT_GTE_24,
    ENEMY_DIED,
    ENEMY_USED_ABILITY,
    END_OF_COMBAT,
    TURN_NUMBER_4,
    TURN_NUMBER_7,
    USED_4_CARDS_IN_TURN
}
