package com.roguelikedeckbuilder.mygame.animated.character;

public enum CharacterTypeName {
    ALIEN,
    ANTEATER,
    BURGER,
    CHIPS,
    EVIL_HH,
    HAMMIE,
    HAM_AND_FIST,
    HAM_SHAMWITCH,
    HELMET_PENGUIN,
    HOT_DOG,
    KING_OF_THE_BURROW,
    KNIGHT,
    MONOLITH,
    PEANUT_BEE,
    POINTER,
    PUFF,
    SAD_DOLLAR,
    SOCK,
    STARER,
    SWORD_FISH,
    UNIMPRESSED_FISH,
}
