package com.roguelikedeckbuilder.mygame.animated.character;

public enum CharacterTypeName {
    BELLFLOWER,
    BIG_BOAR,
    BIG_SLIME,
    BIG_SNAIL,
    BIRD,
    BLUE_MUSHROOM,
    BUFF_PIG,
    DRAGON,
    DYLE,
    FANCY_BIRD,
    FIRE_SPIRIT,
    GOLEM,
    HELMET_PENGUIN,
    KING_PENGUIN,
    LICH,
    LIVING_MONEY,
    MOUSE,
    ORANGE_MUSHROOM,
    PIG,
    PLANT,
    ROBOT,
    ROCK,
    SEAL,
    SKELETON,
    SQUID,
    STUMP,
    THUNDER_SPIRIT,
    TOY_BEAR,
    TRAINING_DUMMY,
    TURNIP,
    WALRUS,
    WARRIOR,
    WRAITH

}
